[package]
name = "brain_fuck_joust"
version = "0.1.0"
authors = ["Arjan Boschman <a.boschman@hotmail.com>"]

[dependencies]

[dependencies.bf_bot_core]
path = "../bf_bot_core"

[dependencies.bf_bot_compiler]
path = "../bf_bot_compiler"